project:
  type: book
  output-dir: docs

date: "last-modified"
date-format: iso
institute: "Wilfrid Laurier University"
number-depth: 2
author: "Dr. Devan Becker"

book:
  title: "Regression Analysis"
  subtitle: Theory, Simulation, and Application
  author: "Dr. Devan Becker"
  date: "last-modified"
  repo-url: https://github.com/DB7-CourseNotes/ST362-Regression-Course-Notes
  repo-actions: [issue, source]  
  page-footer:
    left: |
      Copyright Devan Becker, released under Creative Commons Attribution-ShareAlike 4.0.
  page-navigation: true
  chapters:
    - index.qmd
    - part: OLS Basics
      chapters:
        - L01-Introduction.qmd
        - L02-Fitting_Straight_Lines.qmd
        - L03-Residuals.qmd
        - L04-Matrix_Form.qmd
        - L05-General_Regression.qmd
        - L06-Extra_Sums_of_Squares-1.qmd
        - L07-Exampless.Rmd
        - L09-Serial_Correlation.qmd
        - L10-Hat-Resid_Plots-Cook.qmd
        - L11-Admin_Slides.qmd
        - L12-Extra_Topics.qmd
    - part: Choosing Models
      chapters:
        - L13-Wrong_Model.qmd
        - L14-Nonlinear.qmd
        - L15-Transforming_Response.qmd
        - L16-Dummies.qmd
        - L17-Multicollinearity.qmd
        - L18-Modelling_Poorly.qmd
        - L19-Example_Analysis_mtcars.qmd
        - L20-Degrees_of_Freedom.qmd
    - part: Regularization
      chapters:
        - L21-Regularization.qmd
        - L22-Logistic.qmd
    - part: Review
      chapters:
        - L23-Review.qmd
  appendices:
    - Lb02-OLS_Estimates.Rmd
    - Lb03-MSE.Rmd
    - Lb04-R_Matrix_Form.Rmd
    - Lb05-ANOVA-R2-F_test-CI.Rmd
    - Lb11-R_hat_resids_cook.Rmd
    - Lb12-Corr_in_Betas.qmd
    - Lb13-Wrong_Model.Rmd
    - Lb15-Transformations.Rmd
    - Lb16-Regression_with_Dummies.Rmd
    - Lb17-Multico.Rmd
    - Lb18-Backwards_Selection_is_Bad.Rmd

format:
  html:
    theme:
      light: [flatly, smaller_lists.scss]
      dark: [darkly, smaller_lists.scss]
    mainfont: ubuntu, sans-serif
    execute:
        code-fold: true
        code-summary: "Show the code"
        warning: false

